### ISSUE TITLE
Random OutofBoundsException

### ISSUE THREAD

**Issue by ghost** [Itaros/ChemLab-PublicArea#1]
Happened randomly in my world where I had this mod installed I was not using any block/items from this mod while this crash happened, but it seems to point to this mod.

https://gist.github.com/LawAbidingEnt/f349b59cb94290222bf0

**Comment by Itaros** [comment]
Thank you for report. This is going to be fixed in next version along with some more. This crash occur only in scatterred worldgen mode.

**Comment by Itaros** [comment]
Workaround: 

set 

```
S:clid=ru.itaros.chemlab.loader.worldgen.WorldGenLoaderScattered
```

 to

```
S:clid=ru.itaros.chemlab.loader.worldgen.WorldGenLoaderNative
```

**Comment by ghost** [comment]
That option was already set to Native by default it seems.

**Comment by Itaros** [comment]
Hotfix available: http://chemlab.sg-studio.ru/artifacts/ChemLab-1.7.2-pr-2.01-bde-hotfix.jar 
Experimental.

**Comment by Itaros** [comment]
bde-hotfix was tested by community and considered stable. Issue solved. Thank you for a report.
