### ISSUE TITLE
ChemLab-1.7.10-pr-2.03 crash on server start with Cauldron

### ISSUE THREAD

**Issue by AnodeCathode** [Itaros/ChemLab-PublicArea#3]
Submitted to Cauldron as it doesn't manifest under straight Forge. 

https://github.com/MinecraftPortCentral/Cauldron/issues/1482

**Comment by Itaros** [comment]
Seems to be Cauldron fault: it is passing non-fully-configured tileentity as fully loaded one or something close to this. Will check if I can do anything from my side. Thanks for report.

**Comment by Itaros** [comment]
Seems to be fixed. Thanks to @bloodmc
