### ISSUE TITLE
Crafting Take Over

### ISSUE THREAD

**Issue by madshammy** [Itaros/ChemLab-PublicArea#6]
I have noticed a lot of things that are funky.. first off.. the shear pattern is over written by your mod.  Now it is conflicting with Ancient Warfares crafting as well.

https://gist.github.com/anonymous/5688b1ad3f37895eb1a5 

I asked on his as well.

https://github.com/shadowmage45/AncientWarfare2/issues/194

3 by 3 grid of iron blocks produces a ChemLab Machine Panel instead of the Iron Block

**Comment by madshammy** [comment]
once i uninstalled your mod ever thing works perfectly .. not sure what the issue is with your mod and the others.. they don't like each other.. if you figure something out please let me know.. i would love to mess around with your mod.  Thx

**Comment by Itaros** [comment]
Which version do you use? 

`3 by 3 grid of iron blocks produces a ChemLab Machine Panel`
Feels to be fixed ages ago.

**Comment by madshammy** [comment]
it was 2.03 looks like.

**Comment by Itaros** [comment]
03i1 has this in changelog: 
`HOTFIX: Fixed NEI recipe overview crash`

Try to update to 03i4 and let me know how it behaves.
http://minecraft.curseforge.com/mc-mods/220315-chemlab/files

**Comment by madshammy** [comment]
i actually just looked again sorry.. had to look in solder.. it was 2.03i4

**Comment by Itaros** [comment]
Are you sure? From crashlog:
`chemlab{2.x} [ChemLab] (ChemLab-1.7.10-pr-2.03.jar)`

**Comment by madshammy** [comment]
hmm maybe i looked at wrong version.. i will load it up on a test box i have at home.. i all rdy pulled from our main sever.. i would love to put it back in.. ill give a shot with the i4 here in a bit.. thx for the replys.

**Comment by madshammy** [comment]
https://www.dropbox.com/s/2qr0osj7cum45sy/Screenshot%202014-12-30%2003.45.13.png?dl=0 

yup it was 2.03

**Comment by DarkWolf204** [comment]
im haveing this same issue but i dont have Chem lab so idk whats causeing it everytime i go to use the crafting station i get a hard crash to desktop

**Comment by Itaros** [comment]
It is not The Whole Universe(tm) bug tracker
